### ISSUE TITLE
logging settings rewritten

### ISSUE THREAD

**Issue by didamarkovic** [bengranett/minimask#5]
@bengranett: I think that putting statements like this `logging.basicConfig(level=logging.DEBUG)` into the module files overwrites the logging settings of any code that uses the module. Anyway in Pypelid the logging settings seem to have been broken by switching to minimask (happily this seems to be the only thing that went wrong). :)

**Comment by bengranett** [comment]
Thanks, I removed the logging config line.  9867853aeee4d6
